import os
import yaml
import torch
import argparse

from samplers import get_data_sampler
from tasks import get_task_sampler
from models import get_relevant_baselines


def train_and_save_baseline(config_path, baseline_type="xgboost"):
    # Load training configuration
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)

    # Extract relevant settings
    train_conf = config['training']
    model_conf = config['model']
    out_dir = config.get('out_dir', '.')

    task_name = train_conf['task']
    data_name = train_conf['data']
    batch_size = train_conf['batch_size']
    n_dims = model_conf['n_dims']
    n_points = train_conf['curriculum']['points']['end']
    task_kwargs = train_conf.get('task_kwargs', {})
    num_tasks = train_conf.get('num_tasks', None)

    # Build samplers
    data_sampler = get_data_sampler(data_name, n_dims)
    task_sampler = get_task_sampler(
        task_name,
        n_dims,
        batch_size,
        pool_dict=None,
        num_tasks=num_tasks,
        **task_kwargs
    )

    # Select the baseline model
    baseline_classes = get_relevant_baselines(task_name)
    baseline_model = None
    for candidate in baseline_classes:
        if baseline_type.lower() in candidate.name.lower():
            baseline_model = candidate
            break
    if baseline_model is None:
        raise ValueError(f"Unknown baseline type: {baseline_type}")

    # Prepare output directory
    os.makedirs(out_dir, exist_ok=True)
    save_path = os.path.join(out_dir, f"{baseline_model.name}.pt")

    # Sample one batch of data and labels
    xs = data_sampler.sample_xs(n_points, batch_size)
    ys = task_sampler().evaluate(xs)

    # Train baseline (internal fitting)
    print(f"Training baseline '{baseline_model.name}' on task '{task_name}'...")
    _ = baseline_model(xs, ys)

    # Save trained baseline
    torch.save(baseline_model, save_path)
    print(f"Saved trained baseline model at: {save_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train and save a baseline model on GCP or locally.")
    parser.add_argument(
        "--config", required=True,
        help="Path to the config.yaml generated by train.py (containing training parameters and out_dir)."
    )
    parser.add_argument(
        "--baseline", default="xgboost",
        help="Type of baseline to train (e.g., 'xgboost', 'lasso', 'nn')."
    )
    args = parser.parse_args()

    train_and_save_baseline(args.config, args.baseline)
